spring:
  application:
    name: DictionaryApp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bonappetit?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update


logging:
  level:
    org: WARN                   # Disable the default loggers for org
    blog: WARN                  # Disable the default loggers for blog
    org.hibernate.SQL: DEBUG     # Show SQL executed
    org.hibernate.type.descriptor: TRACE  # Show parameter bindings